### ISSUE TITLE
Erros no s test criados recentes.

### ISSUE THREAD

**Issue by abiliojunior** [abiliojunior/jovemescritor#3]
FAIL["test_should_update_cena", CenasControllerTest, 0.7534624869003892]
 test_should_update_cena#CenasControllerTest (0.75s)
        Expected response to be a <3XX: redirect>, but was a <200: OK>
        test/controllers/cenas_controller_test.rb:38:in `block in <class:CenasControllerTest>'

 FAIL["test_should_create_cena", CenasControllerTest, 0.7668872242793441]
 test_should_create_cena#CenasControllerTest (0.77s)
        "Cena.count" didn't change by 1.
        Expected: 3
          Actual: 2
        test/controllers/cenas_controller_test.rb:19:in `block in <class:CenasControllerTest>'

 FAIL["test_should_create_capitulo", CapitulosControllerTest, 0.8251282386481762]
 test_should_create_capitulo#CapitulosControllerTest (0.83s)
        "Capitulo.count" didn't change by 1.
        Expected: 3
          Actual: 2
        test/controllers/capitulos_controller_test.rb:19:in `block in <class:CapitulosControllerTest>'

 FAIL["test_should_update_capitulo", CapitulosControllerTest, 0.8413650011643767]
 test_should_update_capitulo#CapitulosControllerTest (0.84s)
        Expected response to be a <3XX: redirect>, but was a <200: OK>
        test/controllers/capitulos_controller_test.rb:38:in `block in <class:CapitulosControllerTest>'

 FAIL["test_should_update_projeto", ProjetosControllerTest, 0.9298373339697719]
 test_should_update_projeto#ProjetosControllerTest (0.93s)
        Expected response to be a <3XX: redirect>, but was a <200: OK>
        test/controllers/projetos_controller_test.rb:38:in `block in <class:ProjetosControllerTest>'

 FAIL["test_should_create_projeto", ProjetosControllerTest, 0.9607282476499677]
 test_should_create_projeto#ProjetosControllerTest (0.96s)
abiliojunior:~/workspace/jovemescritor (master) $ rails test
Running via Spring preloader in process 10661
Started with run options --seed 21130

 FAIL["test_should_update_cena", CenasControllerTest, 0.7534624869003892]
 test_should_update_cena#CenasControllerTest (0.75s)
        Expected response to be a <3XX: redirect>, but was a <200: OK>
        test/controllers/cenas_controller_test.rb:38:in `block in <class:CenasControllerTest>'

 FAIL["test_should_create_cena", CenasControllerTest, 0.7668872242793441]
 test_should_create_cena#CenasControllerTest (0.77s)
        "Cena.count" didn't change by 1.
        Expected: 3
          Actual: 2
        test/controllers/cenas_controller_test.rb:19:in `block in <class:CenasControllerTest>'

 FAIL["test_should_create_capitulo", CapitulosControllerTest, 0.8251282386481762]
 test_should_create_capitulo#CapitulosControllerTest (0.83s)
        "Capitulo.count" didn't change by 1.
        Expected: 3
          Actual: 2
        test/controllers/capitulos_controller_test.rb:19:in `block in <class:CapitulosControllerTest>'

 FAIL["test_should_update_capitulo", CapitulosControllerTest, 0.8413650011643767]
 test_should_update_capitulo#CapitulosControllerTest (0.84s)
        Expected response to be a <3XX: redirect>, but was a <200: OK>
        test/controllers/capitulos_controller_test.rb:38:in `block in <class:CapitulosControllerTest>'

 FAIL["test_should_update_projeto", ProjetosControllerTest, 0.9298373339697719]
 test_should_update_projeto#ProjetosControllerTest (0.93s)
        Expected response to be a <3XX: redirect>, but was a <200: OK>
        test/controllers/projetos_controller_test.rb:38:in `block in <class:ProjetosControllerTest>'

 FAIL["test_should_create_projeto", ProjetosControllerTest, 0.9607282476499677]
 test_should_create_projeto#ProjetosControllerTest (0.96s)
        "Projeto.count" didn't change by 1.
abiliojunior:~/workspace/jovemescritor (master) $ rails test
Running via Spring preloader in process 10766
Started with run options --seed 23210

 FAIL["test_should_update_cena", CenasControllerTest, 0.6088349279016256]
 test_should_update_cena#CenasControllerTest (0.61s)
        Expected response to be a <3XX: redirect>, but was a <200: OK>
        test/controllers/cenas_controller_test.rb:38:in `block in <class:CenasControllerTest>'

 FAIL["test_should_create_cena", CenasControllerTest, 0.6249341703951359]
 test_should_create_cena#CenasControllerTest (0.62s)
        "Cena.count" didn't change by 1.
        Expected: 3
          Actual: 2
        test/controllers/cenas_controller_test.rb:19:in `block in <class:CenasControllerTest>'

 FAIL["test_should_create_projeto", ProjetosControllerTest, 0.701784985139966]
 test_should_create_projeto#ProjetosControllerTest (0.70s)
        "Projeto.count" didn't change by 1.
        Expected: 3
          Actual: 2
        test/controllers/projetos_controller_test.rb:19:in `block in <class:ProjetosControllerTest>'

 FAIL["test_should_update_projeto", ProjetosControllerTest, 0.7547940108925104]
 test_should_update_projeto#ProjetosControllerTest (0.75s)
        Expected response to be a <3XX: redirect>, but was a <200: OK>
        test/controllers/projetos_controller_test.rb:38:in `block in <class:ProjetosControllerTest>'

 FAIL["test_should_create_capitulo", CapitulosControllerTest, 0.8828274309635162]
 test_should_create_capitulo#CapitulosControllerTest (0.88s)
        "Capitulo.count" didn't change by 1.
        Expected: 3
          Actual: 2
        test/controllers/capitulos_controller_test.rb:19:in `block in <class:CapitulosControllerTest>'

 FAIL["test_should_update_capitulo", CapitulosControllerTest, 0.9215177148580551]
 test_should_update_capitulo#CapitulosControllerTest (0.92s)
        Expected response to be a <3XX: redirect>, but was a <200: OK>
        test/controllers/capitulos_controller_test.rb:38:in `block in <class:CapitulosControllerTest>'

**Comment by abiliojunior** [comment]
ok
